### ISSUE TITLE
Can't create more spaces

### ISSUE THREAD

**Issue by jeyemwey** [c3nav/c3nav#181]
I'm not sure how i messed up, but I can't create a new space currently. I'm in "Direct Editing" mode, if that helps.
The level already contains a number of spaces which were created the same way.
After hitting "create", the page shows a 500 error, and the log has this:

```log
ERROR 2024-08-13 18:57:11,509 django.request log Internal Server Error: /editor/levels/1/spaces/create
Traceback (most recent call last):
  File "/app/env/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/app/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/app/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/env/lib/python3.11/site-packages/django/views/decorators/http.py", line 154, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/c3nav/editor/views/base.py", line 50, in wrapped
    response = call_api_hybrid_view_for_html(func, request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/c3nav/editor/views/base.py", line 283, in call_api_hybrid_view_for_html
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/c3nav/editor/views/edit.py", line 364, in edit
    obj.save()
  File "/app/c3nav/mapdata/models/geometry/level.py", line 95, in save
    self.register_change()
  File "/app/c3nav/mapdata/models/geometry/level.py", line 80, in register_change
    force = force or self.all_geometry_changed
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/c3nav/mapdata/models/geometry/base.py", line 118, in all_geometry_changed
    return any(getattr(self, attname) != value for attname, value in self._orig.items())
                                                                     ^^^^^^^^^^
AttributeError: 'Space' object has no attribute '_orig'
``` 

Using a docker image built on the code in ea8fe931.

**Comment by codingcatgirl** [comment]
This is likely a glitch caused by something being wrong with an geometry you recently added. If possible, try deleting that object (if you are well-versed in django, through the django console) and creating it again, this should hopefully fix it.

**Comment by codingcatgirl** [comment]
You haven't answered yet. Were you able to resolve the issue? If not, can you send us a database dump of your current situation to c3nav@codingcatgirl.de with instructions on how to reproduce the issue?

**Comment by jeyemwey** [comment]
Stopping the container, removing everything in `data/cache` and restarting did the trick. 🙆‍♀️
I'm not sure how to reproduce the issue, but now it works (as seen yesterday!).

**Comment by codingcatgirl** [comment]
ah, oh well! :D
