### ISSUE TITLE
Exception `CommandError: Unable to serialize database: maximum recursion depth exceeded` when running `python manage.py dumpdata` if area is associated to a location category

### ISSUE THREAD

**Issue by danielegobbetti** [c3nav/c3nav#194]
In a development instance local deployment using sqlite as database, areas and spaces fail to be exported if location groups are set for any object.

To reproduce I created a single area, without any location group:

```
(venv) c3nav:/opt/c3nav/src# python manage.py dumpdata mapdata.area
[{"model": "mapdata.area", "pk": 63, "fields": {"title": {"en": "Water pool"}, "access_restriction": null, "can_search": false, "can_describe": false, "icon": null, "label_settings": null, "label_override": {}, "external_url": null, "import_block_data": false, "import_block_geom": false, "import_tag": null, "space": 61, "geometry": "{\"type\": \"Polygon\", \"coordinates\": [[[233.53, 179.22], [241.07, 179.22], [241.07, 153.74], [240.05, 153.74], [240.05, 152.83], [240.39, 152.83], [240.39, 152.4], [240.2, 152.07], [239.98, 151.85], [239.71, 151.85], [234.88, 151.85], [234.64, 151.99], [234.52, 152.14], [234.44, 152.36], [234.4, 152.47], [234.4, 152.72], [234.71, 152.72], [234.71, 153.75], [233.66, 153.75], [233.53, 179.22]]]}", "slow_down_factor": "1.00", "main_point": null, "groups": []}}]
(venv) c3nav:/opt/c3nav/src# 
```
After adding a Location Group to the area the following happens:
```
(venv) c3nav:/opt/c3nav/src# python manage.py dumpdata mapdata.area
CommandError: Unable to serialize database: maximum recursion depth exceeded
[Exception ignored in: <generator object cursor_iter at 0x7fbb22852f80>
Traceback (most recent call last):
  File "/opt/c3nav/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2129, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception ignored in: <generator object cursor_iter at 0x7fbb22852b00>
Traceback (most recent call last):
  File "/opt/c3nav/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2129, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.

```

I am attaching the output with SQL queries debugging enabled.
[logging.txt](https://github.com/user-attachments/files/16751663/logging.txt)

**Comment by danielegobbetti** [comment]
This is the database point of view:

```sql
sqlite> select * from mapdata_area;
63|{"en": "Water pool"}|0|0|{"type": "Polygon", "coordinates": [[[233.53, 179.22], [241.07, 179.22], [241.07, 153.74], [240.05, 153.74], [240.05, 152.83], [240.39, 152.83], [240.39, 152.4], [240.2, 152.07], [239.98, 151.85], [239.71, 151.85], [234.88, 151.85], [234.64, 151.99], [234.52, 152.14], [234.44, 152.36], [234.4, 152.47], [234.4, 152.72], [234.71, 152.72], [234.71, 153.75], [233.66, 153.75], [233.53, 179.22]]]}|1||61||{}||||0|0|
sqlite> select * from mapdata_area_groups;
2|63|62
sqlite> select * from mapdata_locationgroup where locationslug_ptr_id = 62;
62|{"en": "Water"}|0|0|1|#0090ed||3||1|||{}|dont_offer|{}
```

I can happily provide further information if needed.

**Comment by codingcatgirl** [comment]
We don't support loaddata and dumpdata and importing/exporting from different databases currently, sorry.
