### ISSUE TITLE
Error when using routing (maximum recursion depth)

### ISSUE THREAD

**Issue by johanvdw** [c3nav/c3nav#29]
I've tried migrating the database from FOSDEM ( https://nav.fosdem.org ) to  the latest version of c3nav. On first sight, most things work well, but routing does not:
```

ERROR 2018-12-19 20:06:57,991 django.request log Internal Server Error: /api/routing/route/
Traceback (most recent call last):
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/johan/c3nav/env/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/api.py", line 44, in route
    options=options)
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 447, in get_route
    distances, predecessors = self.shortest_path(restrictions, options=options)
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 403, in shortest_path
    for indices, dir_speed in ((waytype.nonupwards_indices, speed), (waytype.upwards_indices, speed_up)):
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 670, in __getattr__
    return getattr(self.src, name)
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 670, in __getattr__
    return getattr(self.src, name)
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 670, in __getattr__
    return getattr(self.src, name)
  [Previous line repeated 294 more times]
  File "/home/johan/c3nav/c3nav/src/c3nav/routing/router.py", line 668, in __getattr__
    if name in ('__getstate__', '__setstate__'):
RecursionError: maximum recursion depth exceeded in comparison

```

Any clues what is going wrong here?

**Comment by codingcatgirl** [comment]
Yes, you're not on the latest version. That bug has been fixed today. This is also why the stacktrace shows it for the wrong line. You probably just forgot to restart c3nav after pulling the last commit :)

**Comment by codingcatgirl** [comment]
Oh, also definitely you should run clearmapcache and processupdates once to make sure it's fixed.
