### ISSUE TITLE
Error executing python3 manage.py migrate command

### ISSUE THREAD

**Issue by SanFran128** [c3nav/c3nav#38]
I have followed the "Install c3nav manually" installation instructions, changing the libmysqlclient-dev packet to default-libmysqlclient-dev because I get an error saying it isn't available even though another packet is referring to it.

When I arrive to the "Add configuration" section, I don't see how to create a new database, but as it says I can skip that step I continue to the "Migrate the database" section.

Then when I execute the "python3 manage.py migrate" command I get this error:
(env) c3nav@MVC3nav:~/c3nav/c3nav/src$ git pull
Already up-to-date.
(env) c3nav@MVC3nav:~/c3nav/c3nav/src$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/c3nav/c3nav/c3nav/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/c3nav/c3nav/c3nav/src/c3nav/mapdata/models/__init__.py", line 2, in <module>
    from c3nav.mapdata.models.access import AccessRestriction  # noqa
  File "/home/c3nav/c3nav/c3nav/src/c3nav/mapdata/models/access.py", line 16, in <module>
    from c3nav.mapdata.models.base import SerializableMixin, TitledMixin
  File "/home/c3nav/c3nav/c3nav/src/c3nav/mapdata/models/base.py", line 9, in <module>
    from c3nav.mapdata.fields import I18nField
  File "/home/c3nav/c3nav/c3nav/src/c3nav/mapdata/fields.py", line 17, in <module>
    from c3nav.mapdata.utils.geometry import WrappedGeometry, clean_geometry
  File "/home/c3nav/c3nav/c3nav/src/c3nav/mapdata/utils/geometry.py", line 196
    polygons: List[List[LinearRing]] = []
            ^
SyntaxError: invalid syntax

**Comment by codingcatgirl** [comment]
You didn't read the README. It says: 

> **c3nav is currently in development for the 35c3. Documentation for the current state will follow and is currently not available. Sorry.**

Using those instructions this will not work.

Since this is a very basic error i can answer answer: You seem to use an impressively old version of python3, since the "invalid syntax" here has been valid since python 3.5, which was released soon to be 4 years ago. Please update to a current version, at least python 3.6. c3nav is developed for up to date systems.

**Comment by codingcatgirl** [comment]
Honestly, **please** update your python version. You are using python 3.4 or older **which has reached end of life 5 months ago**.

**Comment by SanFran128** [comment]
I use version 3.5, but thank you for your answer. I will update and try again

**Comment by codingcatgirl** [comment]
Huh, it's possible that this was a type hinting syntax that was introduced with python 3.6 then.

You can expect c3nav to start using any new python versions within a few months after their release. It's why we really can't recommend running c3nav on systems like debian that have a rather…sentimental approach to updates.

**Comment by SanFran128** [comment]
I'm very sorry for the inconvenience. The install guide I found here was for debian. I've upgraded to debian 10 and python 3.7
I have followed the instructions, and all has gone well, once I have added the installation of python3-tk packet to avoid an error related to the module tkinter not being found.
Thank you very much for your patience and support.

**Comment by codingcatgirl** [comment]
As i said before, support for running c3nav is currently not available. We are working on documenting the installation, configuration and usage.
